name: Manual Version Bump and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump'
        required: true
        default: 'patch'
      branch:
        description: 'Branch to run on'
        required: true
        default: 'master'
  pull_request:
    types:
      - closed
permissions:
  contents: write
  packages: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: lui-ui/lui-vue
          bump-minor-pre-major: ${{ github.event.inputs.version }}
          default-branch: ${{ github.event.inputs.branch }}

  release:
    runs-on: ubuntu-latest
    if: |
      contains(toJson(github.event.pull_request.labels.*.name), 'autorelease: pending') == true && github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Get version
        id: package-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.version }}
          files: ./package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
